chore(deps): update all non-major dependencies, update tests
Update useElevationProfileChart tests to fix this error after upgrading
happy-dom:
TypeError: 'defineProperty' on proxy: trap returned falsish for property 'opacity'
 ❯ makeTooltipRef src/composables/__tests__/useElevationProfileChart.spec.ts:38:10

Explanation: Using Object.defineProperty is a workaround for setting a
read-only property like clientWidth (done elsewhere in the same file). It is
not required for setting opacity because opacity is not read-only. It leads
to an error in happy-dom after the upgrade due to some changes in happy-dom
internals.